name: ci_pr_format_test
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  format:
    uses: ./.github/workflows/job_format.yml
  test:
    uses: ./.github/workflows/job_test.yml
    secrets: inherit
